apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: frontend
  image: nixry-hivqxraftv.krampoline.com
  imagePullPolicy: Always